spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod?allowPublicKeyRetrieval=true&useSSL=false
    username: sfg_prod_user
    password: guru
#    initialization-mode: ALWAYS
    platform: mysql
    
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show-sql: true
    